services:
  redis:
    image: redis:7.4-rc
    container_name: redis_app
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data

  web:
    container_name: web_app
    build:
      context: ./web
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  redis_data: